### ISSUE TITLE
[Question] minBitSize?

### ISSUE THREAD

**Issue by kirillDanshin** [valyala/bytebufferpool#1]
Hi again @valyala :)
In [this line](https://github.com/valyala/bytebufferpool/blob/master/pool.go#L10) you wrote that minBitSize is a cache line size. It equals to six for now. As far as I know cache line size typically equals to 64 bytes. Why it equals to six?
Thanks :)

**Comment by valyala** [comment]
@kirillDanshin , see the clarified comment [in this CL](https://github.com/valyala/bytebufferpool/commit/fd4be3f08f2b03b0600ca5b5b49497b5787a7995) :)

**Comment by kirillDanshin** [comment]
@valyala thanks :3
